import turtle
wn = turtle.Screen()
turtle.bgcolor('black')
turtle.shape('turtle')
track = turtle.Turtle()
start = turtle.Turtle()
pointer = turtle.Turtle()
track2 = turtle.Turtle()
track3 = turtle.Turtle()
track4 = turtle.Turtle()
track5 = turtle.Turtle()
move = 1

track5.speed("fastest")
for i in range(10):
    for i in range(4):
        track5.pu()
        track5.goto(500, 200)
        track5.pd()
        track5.color('cyan')
        track5.pensize(3)
        track5.circle(50, steps=4)
        track5.right(100)
track5.speed("fastest")
for i in range(6):
    for i in range(4):
        track5.pu()
        track5.goto(0, 0)
        track5.pd()
        track5.color('light green')
        track5.pensize(3)
        track5.circle(100, steps=6)
        track5.right(100)
track2.speed("fastest")
for i in range(10):
    for i in range(2):
        track2.pensize(5)
        track2.goto(270, 0)
        track2.color("green")
        track2.forward(100)
        track2.right(60)
        track2.color("cyan")
        track2.forward(50)
        track2.right(120)
    track2.right(30)
track.speed("fastest")
for i in range(10):
    for i in range(2):
        track.pensize(7)
        track.goto(-270, 0)
        track.color("purple")
        track.forward(100)
        track.circle(5, steps=4)
        track.right(60)
        track.color("violet")
        track.forward(50)
        track.right(120)
    track.right(30)
start.speed("fastest")
track5.speed("fastest")
for i in range(10):
    for i in range(4):
        track5.pu()
        track5.goto(-500, 200)
        track5.pd()
        track5.color('yellow')
        track5.pensize(3)
        track5.circle(50, steps=4)
        track5.right(100)
track5.speed("fastest")
for i in range(10):
    for i in range(4):
        track5.pu()
        track5.goto(-500, -200)
        track5.pd()
        track5.color('white')
        track5.pensize(3)
        track5.circle(50, steps=3)
        track5.right(100)
track5.speed("normal")
for i in range(10):
    for i in range(4):
        track5.pu()
        track5.goto(500, -200)
        track5.pd()
        track5.color('pink')
        track5.pensize(3)
        track5.circle(50, steps=3)
        track5.right(100)
for i in range(20):
    for i in range(2):
        start.pensize(2)
        start.goto(0, 300)
        start.color("red")
        start.forward(100)
        start.circle(6, steps=3)
        start.right(70)
        start.color("yellow")
        start.forward(50)
        start.right(120)
    start.left(30)
start.speed('fastest')
for i in range(20):
    for i in range(2):
        start.pensize(2)
        start.pu()
        start.goto(0, -300)
        start.color("pink")
        start.pd()
        start.forward(100)
        start.circle(6, steps=3)
        start.right(70)
        start.color("orange")
        start.forward(50)
        start.right(120)
    start.left(30)
track3.speed("fastest")
for i in range(10):
    for i in range(2):
        track3.pensize(3)
        track3.goto(-320, 300)
        track3.color("light green")
        track3.begin_fill()
        track3.forward(30)
        track3.right(50)
        track3.color("green")
        track3.forward(50)
        track3.circle(5, steps=6)
        track3.right(120)
        track3.end_fill()
    track3.right(60)
track3.speed("fastest")
for i in range(10):
    for i in range(2):
        track3.pensize(3)
        track3.pu()
        track3.goto(320, -300)
        track3.pd()
        track3.color("red")
        track3.begin_fill()
        track3.forward(30)
        track3.right(50)
        track3.color("orange")
        track3.forward(50)
        track3.circle(5, steps=6)
        track3.right(120)
        track3.end_fill()
    track3.right(100)
track3.speed("fastest")
for i in range(10):
    for i in range(2):
        track3.pensize(3)
        track3.pu()
        track3.goto(320, 300)
        track3.pd()
        track3.color("light blue")
        track3.begin_fill()
        track3.forward(30)
        track3.right(50)
        track3.color("blue")
        track3.forward(50)
        track3.circle(5, steps=6)
        track3.right(120)
        track3.end_fill()
    track3.right(60)
track3.speed("fastest")
for i in range(10):
    for i in range(2):
        track3.pensize(3)
        track3.pu()
        track3.goto(-320, -300)
        track3.pd()
        track3.color("orange")
        track3.begin_fill()
        track3.forward(30)
        track3.right(50)
        track3.color("red")
        track3.forward(50)
        track3.circle(5, steps=6)
        track3.right(120)
        track3.end_fill()
    track3.right(60)

track5.speed("fastest")
for i in range(10):
    for i in range(4):
        track5.pu()
        track5.goto(600, 0)
        track5.pd()
        track5.color('white')
        track5.pensize(1)
        track5.circle(40, steps=5)
        track5.right(100)
track5.speed("fastest")

track5.speed("fastest")
for i in range(10):
    for i in range(4):
        track5.pu()
        track5.goto(600, 0)
        track5.pd()
        track5.color('green')
        track5.pensize(1)
        track5.circle(20, steps=9)
        track5.right(100)
track5.speed("fastest")
artist = turtle.Turtle()
artist.pencolor("red")
for i in range(50):
    artist.pu()
    artist.goto(-600, 0)
    artist.pd()
    artist.forward(100)
    artist.left(123)
turtle.done()
