import turtle
turtle.bgcolor('black')
wn = turtle.Screen()
tracker_pointer = turtle.Turtle()

going = 1
tracker_pointer.speed("fastest")
for i in range(360):

    tracker_pointer.write("Welcome ", 'false', 'center',
                          font=('Showcard gothic', 50))
    tracker_pointer.penup()
    tracker_pointer.goto(-200, 100)
    tracker_pointer.pendown()
    tracker_pointer.color("orange")
    tracker_pointer.right(going)
    tracker_pointer.forward(100)
    tracker_pointer.penup()
    tracker_pointer.color("white")
    tracker_pointer.pendown()
    tracker_pointer.right(30)
    tracker_pointer.forward(60)
    tracker_pointer.pendown()
    tracker_pointer.color("light green")
    tracker_pointer.left(10)
    tracker_pointer.forward(50)
    tracker_pointer.right(70)
    tracker_pointer.penup()
    tracker_pointer.pendown()
    tracker_pointer.color('light blue')
    tracker_pointer.forward(50)
    tracker_pointer.color('light green')
    tracker_pointer.pu()
    tracker_pointer.pd()
    tracker_pointer.color("light blue")
    tracker_pointer.forward(100)
    tracker_pointer.color('brown')
    tracker_pointer.forward(200)
    tracker_pointer.pu()
    tracker_pointer.pd()
    tracker_pointer.color('light green')
    tracker_pointer.circle(2)
    tracker_pointer.color('light blue')
    tracker_pointer.circle(4)
    tracker_pointer.pu()
    tracker_pointer.fd(20)
    tracker_pointer.pd()
    tracker_pointer.circle(6)
    tracker_pointer.pu()
    tracker_pointer.fd(40)
    tracker_pointer.pd()
    tracker_pointer.circle(8)
    tracker_pointer.pu()
    tracker_pointer.fd(80)
    tracker_pointer.pd()
    tracker_pointer.circle(10)
    tracker_pointer.pu()
    tracker_pointer.fd(120)
    tracker_pointer.pd()
    tracker_pointer.circle(20)
    tracker_pointer.color('yellow')
    tracker_pointer.circle(10)
    tracker_pointer.pu()
    tracker_pointer.pd()
    tracker_pointer.color('white')
    tracker_pointer.forward(150)
    tracker_pointer.color('red')
    tracker_pointer.fd(50)
    tracker_pointer.color('blue')
    tracker_pointer.begin_fill()
    tracker_pointer.penup()
    tracker_pointer.home()
    going = going+1
tracker_pointer.penup()
tracker_pointer.forward(50)
turtle.done()
